---
- hosts: "local"
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: Start plex
      docker_container:
        name: plex
        image: lscr.io/linuxserver/plex
        state: started
        recreate: yes
        restart_policy: always
        network_mode: "host"
        volumes:
          - /home/{{ setup_user }}/plex/config:/config
          - /home/{{ setup_user }}/media:/data
        env:
          PLEX_CLAIM: claim-TaLvmW8TM4Jjr1cssN3s
          PUID: "1000"
          PGID: "1000"
          VERSION: docker
