---
- hosts: "local"
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: Start Uptime Kuma
      docker_container:
        name: uptime-kuma
        image: louislam/uptime-kuma
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "3001:3001"
        volumes:
          - /home/{{ setup_user }}/uptime-kuma:/app/data
