---
- hosts: "local"
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: Start Yatch
      docker_container:
        name: yatch
        image: selfhostedpro/yacht
        state: started
        recreate: yes
        restart_policy: always
        networks:
          - name: "eva"
        ports:
          - "7999:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/{{ setup_user }}/yatch:/config
