---
- hosts: "do"
  vars_files:
    - vars/default.yml
  tasks:
    - name: Copy Nginx config files
      copy:
        src: config/nginx/
        dest: /home/{{ do_user }}/nginx
        owner: "{{ do_user }}"
        group: "{{ do_user }}"
        mode: 0644
    - name: Start Nginx
      docker_container:
        name: nginx
        image: nginx
        state: started
        recreate: yes
        restart_policy: always
        networks:
          - name: "killcss"
        ports:
          - "80:80/tcp"
          - "443:443"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
          - ./nginx/html:/usr/share/nginx/html:ro"
          - ./certbot/www:/var/www/certbot/:ro
          - ./certbot/conf/:/etc/nginx/ssl/:ro
