- name: "Setup Digital Ocean"
  hosts: "do"
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "mc",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: pip install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: Setup killcss network
      docker_network:
        name: killcss
