- name: "Setup Digital Ocean"
  hosts: "do"
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Upgrade Packages
      apt:
        name: "*"
        state: latest
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "mc",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: pip install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: Add {{ do_user }} to docker group
      user:
        name: "{{ do_user }}"
        groups: "docker"
        append: "yes"

    - name: Setup killcss network
      docker_network:
        name: killcss
