---
- hosts: "do"
  vars_files:
    - vars/default.yml
  tasks:
    - name: Copy SSL Config files (1)
      copy:
        src: config/ssl-1/
        dest: /home/{{ do_user }}/ssl-1
        owner: "{{ do_user }}"
        group: "{{ do_user }}"
        mode: 0644

    - name: Start Nginx
      docker_container:
        name: nginx
        image: nginx
        state: started
        recreate: yes
        restart_policy: always
        networks:
          - name: "killcss"
        ports:
          - "80:80/tcp"
        volumes:
          - ./ssl-1/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./certbot/www:/var/www/certbot/:ro
          - ./certbot/conf/:/etc/nginx/ssl/:ro

    - name: Start Certbot
      docker_container:
        name: certbot
        image: certbot/certbot
        command: certonly --webroot --webroot-path /var/www/certbot/ --non-interactive --agree-tos -m {{ do_email }} -d killcss.xyz -d www.killcss.xyz
        state: started
        recreate: no
        restart_policy: no
        volumes:
          - ./certbot/www/:/var/www/certbot/:rw
          - ./certbot/conf/:/etc/letsencrypt/:rw
